# K Nearest Neighbors

---

## Programming Environment

In [1]:
import numpy  as np
np.set_printoptions(suppress=True)
import pandas as pd

---

[MATRIX NOTATION]

A matrix $X$ of type $(I, J)$ is a function $f$ from $I \times J$.

$I = \{1, \dots, m\}$ is an index set for rows and $J = \{1, \dots, n\}$ is an index set for columns for some $m, n \in \mathbb{N}$.

Since a matrix is just a function its element in the $i$-th row and $j$-th column is just $X(i, j)$. $X(i, j)$ is written $x_{ij}$. $(x_{ij})$ is an abbreviation for $(x_{ij} : i \in I, j \in J)$ which is the function analogue for set-builder notation $\{ x_{ij} : i \in I, j \in J \}$

$X_{[m \times n]}$ explicitly specifies the dimensions.

$
\begin{aligned}
\sum_{j=1}^n x_{ij}
\end{aligned}
$
represents the sum of the $i$-th row.

[EUCLIDEAN DISTANCE between two vectors]

$
\begin{aligned}
\mathbf{x} &= \langle x_1, \dots, x_n \rangle
\\
\mathbf{y} &= \langle y_1, \dots, y_n \rangle
\\
\|\mathbf{x} - \mathbf{y}\|_2
&= \sqrt{(x_1 - y_1)^2 + \dots + (x_n - y_n)^2}
= \sqrt{\sum_{i=1}^n (x_i - y_i)^2}
\\
\|\mathbf{x} - \mathbf{y}\|_2^2
&= (x_1 - y_1)^2 + \dots + (x_n - y_n)^2
= \sum_{i=1}^n (x_i - y_i)^2
\end{aligned}
$

[L2 EUCLIDEAN NORM]

$
\begin{aligned}
\mathbf{x} &= \langle x_1, \dots, x_n \rangle
\\
\|\mathbf{x}\|_2
&= \sqrt{\mathbf{x} \cdot \mathbf{x}}
= \sqrt{x_1^2 + \dots + x_n^2}
= \sqrt{\sum_{i=1}^n x_i^2}
\\
\|\mathbf{x}\|_2^2
&= \mathbf{x} \cdot \mathbf{x}
= x_1^2 + \dots + x_n^2
= \sum_{i=1}^n x_i^2
\end{aligned}
$

[DISTANCE MATRIX]

A distance matrix $\text{dist}$ is a square matrix that captures the pairwise distances between a set of vectors $x_1, \dots, x_n$. The element $\text{dist}_{ij}$ represents the distance between $x_i$ and $x_j$. Tthe matrix is symmetric, since $\text{dist}_{ij}=\text{dist}_{ji}$, and the dimensionality of the matrix is $n \times n$.

The matrix $X_{[n \times d]}$ represents a set of $n$ data points of dimension $d$ where $i, j \in \{ 1, \dots, n \}$ are indices over the data points and $k \in \{ 1, \dots, d \}$ is an index over the dimension.

$X_i$ (or $X_j$) is the $i$-th (or $j$-th) data point in the data set (or the $i$-th (or $j$-th) row vector $\mathbf{x_i}$ (or $\mathbf{x_j}$) in the matrix).

$X_{ik}$ is the $k$-th element of the $i$-th row vector of the matrix $X$ and can be written $x_{ik}$.

$
\begin{aligned}
X      &&              && \text{matrix} \\
X_i    && \mathbf{x_i} && \text{vector} \\
X_{ik} && x_{ik}       && \text{scalar} \\
\end{aligned}
$

$
\begin{aligned}
\text{dist}_{ij} &= \sqrt{\sum_{k=1}^d (x_{ik} - x_{jk})^2} \\
                 &= \sqrt{\sum_{k=1}^d (x^2_{ik} - 2x_{ik}x_{jk} + x^2_{jk})} \\
                 &= \sqrt{\sum_{k=1}^d x^2_{ik} - 2 \sum_{k=1}^d x_{ik}X_{jk} + \sum_{k=1}^d x^2_{jk}} \\
                 &= \mathbf{x_i} \cdot \mathbf{x_i} - 2 \mathbf{x_i} \cdot \mathbf{x_j} + \mathbf{x_j} \cdot \mathbf{x_j} \\
                 &= x_i^T x_i - 2 x_i^T x_j + x_j^T x_j \\
\end{aligned}
$

### Example

$
\begin{aligned}
X_{[n \times k]} &=
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 \\
\end{bmatrix}
\\
X^{\circ 2} &=
\begin{bmatrix}
1^2 & 2^2 \\
3^2 & 4^2 \\
5^2 & 6^2 \\
\end{bmatrix}
= \begin{bmatrix}
 1 &  4 \\
 9 & 16 \\
25 & 36 \\
\end{bmatrix}
\\
\sum_{k=1}^d x^{\circ 2}_{ik}
&= \begin{bmatrix}
 1 +  4 \\
 9 + 16 \\
25 + 36 \\
\end{bmatrix}
= \begin{bmatrix}
 5 \\
25 \\
61 \\
\end{bmatrix}
\end{aligned}
$

In [3]:
X   = np.array([1, 2, 3, 4, 5, 6]).reshape( 3,  2)
xsq = np.sum(np.square(X), axis=1).reshape(-1,  1)
ysq = np.sum(np.square(X), axis=1).reshape( 1, -1)
xy  = X @ X.T
xy

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [4]:
dist = np.sqrt(xsq - 2 * xy + ysq)
dist

array([[0.        , 2.82842712, 5.65685425],
       [2.82842712, 0.        , 2.82842712],
       [5.65685425, 2.82842712, 0.        ]])

---

## Wine Data Set

In [282]:
D = np.loadtxt(fname='wine/wine.data', delimiter=',')
np.info(D)

class:  ndarray
shape:  (178, 14)
strides:  (112, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x14b9cd800
byteorder:  little
byteswap:  False
type: float64


In [283]:
X = D[:,1:]
X.shape

(178, 13)

In [301]:
x2 = np.sum(X**2, axis=1).reshape(-1,  1)
y2 = np.sum(X**2, axis=1).reshape( 1, -1)
xy = X @ X.T

print(x2.shape)
print(xy.shape)
print(y2.shape)

dist = np.sqrt(x2 - 2*xy + y2)

pd.DataFrame(dist).round(2)

(178, 1)
(178, 178)
(1, 178)


/var/folders/89/5r24znsj4jbfr7zrccy5yn0c0000gn/T/ipykernel_25678/462695083.py:9: RuntimeWarning: invalid value encountered in sqrt
  dist = np.sqrt(x2 - 2*xy + y2)


0       1       2       3       4       5       6       7       8    \
0      0.00   31.27  122.83  415.25  330.17  385.30  227.13  230.09   36.12   
1     31.27    0.00  135.22  430.25  315.67  400.21  240.06  245.98    6.79   
2    122.83  135.22    0.00  295.26  450.33  265.26  105.21  111.83  140.15   
3    415.25  430.25  295.26    0.00  745.04   30.09  190.80  185.20  435.31   
4    330.17  315.67  450.33  745.04    0.00  715.05  555.48  560.02  310.80   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
173  326.66  310.24  445.08  740.25   24.15  710.24  550.06  555.64  305.13   
174  316.11  300.27  435.04  730.12   22.42  700.13  540.11  545.37  295.21   
175  230.24  216.22  350.57  645.07  100.25  615.10  455.71  460.05  211.44   
176  225.22  211.21  345.56  640.06  105.18  610.09  450.70  455.04  206.44   
177  506.06  490.24  625.07  920.20  176.51  890.20  730.09  735.48  485.15   

        9    ...     168     169     170      171     172     173     174  \
0     35.27  ...  315.93  435.39  555.90   596.46  406.66  326.66  316.11   
1      7.83  ...  300.38  420.44  540.08   580.26  390.25  310.24  300.27   
2    140.07  ...  435.08  555.17  675.03   715.18  525.13  445.08  435.04   
3    435.26  ...  730.10  850.05  970.17  1010.38  820.31  740.25  730.12   
4    310.70  ...   20.78  105.37  226.11   267.01   79.95   24.15   22.42   
..      ...  ...     ...     ...     ...      ...     ...     ...     ...   
173  305.10  ...   15.06  111.41  230.04   270.18   80.19    0.00   12.60   
174  295.14  ...    3.89  120.44  240.12   280.50   90.77   12.60    0.00   
175  211.26  ...   86.46  205.23  325.93   366.59  177.40   98.28   86.99   
176  206.26  ...   91.36  210.22  330.90   371.56  182.32  103.14   91.86   
177  485.10  ...  190.22   71.82   50.50    90.73  100.24  180.06  190.11   

        175     176     177  
0    230.24  225.22  506.06  
1    216.22  211.21  490.24  
2    350.57  345.56  625.07  
3    645.07  640.06  920.20  
4    100.25  105.18  176.51  
..      ...     ...     ...  
173   98.28  103.14  180.06  
174   86.99   91.86  190.11  
175    0.00    5.36  276.09  
176    5.36    0.00  281.07  
177  276.09  281.07    0.00  

[178 rows x 178 columns]

In [285]:
sum(x2 - 2 * (X @ X.T) + y2 < 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [311]:
np.argwhere(sum(x2 - 2*xy + y2 < 0))

array([[116]])

In [313]:
distsq = x2 - 2*xy + y2
distsq

array([[     0.    ,    977.501 ,  15087.4924, ...,  53010.4682,
         50721.8791, 256096.0836],
       [   977.501 ,      0.    ,  18285.7176, ...,  46751.6212,
         44611.1589, 240330.6182],
       [ 15087.4924,  18285.7176,      0.    , ..., 122900.1578,
        119413.5463, 390712.7272],
       ...,
       [ 53010.4682,  46751.6212, 122900.1578, ...,      0.    ,
            28.7177,  76223.4878],
       [ 50721.8791,  44611.1589, 119413.5463, ...,     28.7177,
             0.    ,  78999.7785],
       [256096.0836, 240330.6182, 390712.7272, ...,  76223.4878,
         78999.7785,      0.    ]])

In [ ]:
np.argwhere(distsq[116] < 0)

array([[116]])

In [ ]:
distsq[116,116]

-5.820766091346741e-11

In [317]:
np.sqrt(-0.)

-0.0

In [323]:
-0. == 0

True

---

## Resources

* [ [rp](https://realpython.com/knn-python/) ] Korstanje, Joos. (07 Apr 2021). "The k-Nearest Neighbors (kNN) Algorithm in Python". RealPython.
* [ [a](https://jaykmody.com/blog/distance-matrices-with-numpy/) ] Mody, Jay. (04 Apr 2021). "Computing Distance Matrices with NumPy".
* https://numerics.mathdotnet.com/Distance
* http://cs231n.stanford.edu/

---

## Terms

* [ [w](https://en.wikipedia.org/wiki/Distance_matrix) ] Distance Matrix
* [ [w](https://en.wikipedia.org/wiki/Euclidean_distance) ] Euclidean Distance
* [ [w](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) ] Hadamard Product
* [ [w](https://en.wikipedia.org/wiki/Norm_(mathematics)) ] Norm

---