# NumPy Tutorial - Saving and sharing your NumPy arrays

---

In [1]:
import numpy as np
np.__version__

'1.25.2'

---

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = x ** 2
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
np.savez(file = 'x_y-squared.npz', x_axis = x, y_axis = y)

In [5]:
del x, y

In [6]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [7]:
load_xy = np.load(file = 'x_y-squared.npz')
load_xy.files

['x_axis', 'y_axis']

In [8]:
whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [9]:
x = load_xy['x_axis']
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = load_xy['y_axis']
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

---

In [12]:
array_out = np.block(arrays = [x[:, np.newaxis], y[:, np.newaxis]])
array_out

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64],
       [ 9, 81]])

In [14]:
np.savetxt(fname = 'x_y-squared.csv', X = array_out, header = 'x, y', delimiter = ',')

In [15]:
! head x_y-squared.csv

# x, y
0.000000000000000000e+00,0.000000000000000000e+00
1.000000000000000000e+00,1.000000000000000000e+00
2.000000000000000000e+00,4.000000000000000000e+00
3.000000000000000000e+00,9.000000000000000000e+00
4.000000000000000000e+00,1.600000000000000000e+01
5.000000000000000000e+00,2.500000000000000000e+01
6.000000000000000000e+00,3.600000000000000000e+01
7.000000000000000000e+00,4.900000000000000000e+01
8.000000000000000000e+00,6.400000000000000000e+01


In [16]:
del x, y

In [18]:
load_xy = np.loadtxt(fname = 'x_y-squared.csv', delimiter = ',')
load_xy.shape

(10, 2)

In [19]:
x = load_xy[:, 0]
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
y = load_xy[:, 1]
y

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

---