# NumPy Tutorial - Saving and sharing your NumPy arrays

---

In [12]:
import numpy as np

import datetime
from   importlib.metadata import version
import os
import platform as p
import sys

pad = 20
print(  f"\n{'Executed' : <{pad}} : {datetime.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %z %Z')}"
        f"\n{'Platform' : <{pad}} : {p.platform(aliased = False, terse = False)}"
        f"\n{'Conda'    : <{pad}} : {os.environ['CONDA_DEFAULT_ENV'] or sys.executable.split('/')[-3]}"
        f"\n{'Python'   : <{pad}} : {p.python_implementation()} {p.python_version()} {sys.executable}")
print(*[f'{name : <{pad}} : {version(name)}'
        for name in ['NumPy']], sep = '\n')


Executed             : 2023-09-04 20:43:46 -0400 EDT
Platform             : macOS-13.5.1-arm64-arm-64bit
Conda                : ml
Python               : CPython 3.11.5 /Users/df/anaconda3/envs/ml/bin/python
NumPy                : 1.23.5


---

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = x ** 2
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
np.savez(file = 'x_y-squared.npz', x_axis = x, y_axis = y)

In [5]:
del x, y

In [6]:
%whos

Variable   Type        Data/Info
--------------------------------
datetime   module      <module 'datetime' from '<...>/python3.11/datetime.py'>
np         module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
os         module      <module 'os' (frozen)>
p          module      <module 'platform' from '<...>/python3.11/platform.py'>
pad        int         20
sys        module      <module 'sys' (built-in)>
version    function    <function version at 0x1076704a0>


In [7]:
load_xy = np.load(file = 'x_y-squared.npz')
load_xy.files

['x_axis', 'y_axis']

In [8]:
whos

Variable   Type        Data/Info
--------------------------------
datetime   module      <module 'datetime' from '<...>/python3.11/datetime.py'>
load_xy    NpzFile     NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np         module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
os         module      <module 'os' (frozen)>
p          module      <module 'platform' from '<...>/python3.11/platform.py'>
pad        int         20
sys        module      <module 'sys' (built-in)>
version    function    <function version at 0x1076704a0>


In [9]:
x = load_xy['x_axis']
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = load_xy['y_axis']
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

---

---